version: 0.2

env:
  variables:
    IMAGE_NAME: "sysdiglabs/dummy-vuln-app:latest"
    SCAN_IMAGE_NAME: "sysdiglabs/secure_inline_scan:latest"
  parameter-store:
    DOCKER_LOGIN_USER: dockerLoginUser
    DOCKER_LOGIN_PASSWORD: dockerLoginPassword
    SYSDIG_SECURE_TOKEN: sysdigApiToken
    

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
    - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
    - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"       

  pre_build:
    commands:
    - docker pull $SCAN_IMAGE_NAME

  build:
    commands:
    - docker build . -t $IMAGE_NAME

  post_build:
    commands:
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock $SCAN_IMAGE_NAME --sysdig-url https://secure.sysdig.com --sysdig-token $SYSDIG_SECURE_TOKEN --storage-type docker-daemon $IMAGE_NAME
    - docker login -u $DOCKER_LOGIN_USER -p $DOCKER_LOGIN_PASSWORD
    - docker push $IMAGE_NAME
