version: 0.2

env:
  variables:
    IMAGE_NAME: "sysdiglabs/dummy-vuln-app:latest"
    SCAN_IMAGE_NAME: "quay.io/sysdig/secure-inline-scan:2"
  parameter-store:
    DOCKER_LOGIN_USER: dockerLoginUser
    DOCKER_LOGIN_PASSWORD: dockerLoginPassword
    SYSDIG_SECURE_TOKEN: sysdigApiToken

phases:
  build:
    commands:
    - docker build . -t $IMAGE_NAME

  post_build:
    commands:
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock $SCAN_IMAGE_NAME --sysdig-url https://secure.sysdig.com --sysdig-token $SYSDIG_SECURE_TOKEN --storage-type docker-daemon $IMAGE_NAME
    - docker login -u $DOCKER_LOGIN_USER -p $DOCKER_LOGIN_PASSWORD
    - docker push $IMAGE_NAME
